CREATE TABLE TASKS
(
    ID          VARCHAR(36)  NOT NULL,
    TITLE       VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    DEADLINE    TIMESTAMP(9)    NOT NULL,
    STATUS      VARCHAR(10)
);