CREATE TABLE TASKS
(
    ID          VARCHAR(36)  NOT NULL PRIMARY KEY,
    TITLE       VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    DEADLINE    TIMESTAMP    NOT NULL,
    STATUS      NUMERIC(1)
);